name: ServerLock
main: ru.SemperAnte.ServerLock.Main.ServerLock
version: 2.0
author: SemperAnte
depend: [SemperAnteAPI]
commands:
  ServerLock:
    description: Plugin main command
    aliases: [sl, SLock]
    default: false
